### ISSUE TITLE
Add School Information cascade

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/siwins#44]
- School type
- School name
- School code

---

**Todo**
- [x] Create new migration for cascade (parent children)
- [x] Create a seeder (fetch data from flow cascadeResource)
- [x] Create cascade dump from local db to csv, and use that as resource to seed on test/prod
