### ISSUE TITLE
Add new column to question & option table

### ISSUE THREAD

**Issue by wayangalihpratama** [akvo/siwins#54]
- Related to the below asana task:
  - https://app.asana.com/0/1204193430573075/1204388170647398
  - https://app.asana.com/0/1204193430573075/1204386590989280

---

**Todo:**
- [x] Add attributes & display name column to question table
  - [x] Modify models
  - [x] Modify form seeder (include crud and test)
- [x] Add color & info text column to option table
  - [x] Modify models
  - [x] Modify form/option seeder (include crud and test)
- [x] Modify question indicator endpoint to show question attributes, display_name and option color, description
